[package]
name = "nft-escrow-meta"
version = "0.0.0"
edition = "2018"
publish = false
authors = ["you"]

[dev-dependencies]

[dependencies.nft-escrow]
path = ".."

[dependencies.multiversx-sc-meta-lib]
version = "0.52.3"
default-features = false
